import Navbar from "@/components/Navbar";
import './globals.css';
import { Inter } from 'next/font/google';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { getSession } from '@auth0/nextjs-auth0';
import conn from '@/libs/mysql';  // Importa la conexión a la base de datos
import bcrypt from 'bcrypt';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function insertUserIntoDatabase(user) {
  if (!user) return;

  const { email, name, sub } = user;
  const password = bcrypt.hashSync(sub, 10); // Hasheamos el sub de Auth0 como contraseña

  const [rows] = await conn.query('SELECT * FROM User WHERE email = ?', [email]);

  if (rows.length === 0) {
    // Insertar nuevo usuario en la base de datos
    const role_id = 3; // Asignar un rol predeterminado
    await conn.query(
      'INSERT INTO User (email, name, password, role_id) VALUES (?, ?, ?, ?)',
      [email, name, password, role_id]
    );
  }
}

export default async function RootLayout({ children }) {
  const session = await getSession();
  const user = session?.user;
  console.log(user);

  // Inserta el usuario en la base de datos
  await insertUserIntoDatabase(user);

  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full flex flex-col`}>
        <UserProvider>
          <Navbar />
          <div className="flex-grow">
            {children}
          </div>
        </UserProvider>
      </body>
    </html>
  );
}